// <auto-generated />
namespace se_CodeFirst_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClaimBasedAuthorization2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClaimBasedAuthorization2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711042118455_ClaimBasedAuthorization2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
